### ISSUE TITLE
UnsatisfiedLinkError : Can't find dependent libraries 

### ISSUE THREAD

**Issue by tofik2943** [hdonk/javelin#1]
java.lang.UnsatisfiedLinkError: javelin.dll: Can't find dependent libraries. 

Windows 10

I can attach more information, but which?

**Comment by hdonk** [comment]
Hi,
   You need to build the Visual Studio project to generate the dll.

**Comment by tofik2943** [comment]
I have generated .dll from Visual Studio. Inserted dependecies for working Jni as for my every Jni project. Generated .dll seems ok, when i inspect it with dumpbin i have 
![image](https://user-images.githubusercontent.com/49273764/188881397-bcf259ea-924b-459d-abcb-85d696837160.png)
. Exception occurs when I'm using  'System.load'. I dont know which additional dependencies .dll is expecting. Thank's for reply

**Comment by tofik2943** [comment]
I'm sorry. My issue is irrelevant. U have clearly declared dependencies. 
![image](https://user-images.githubusercontent.com/49273764/188886302-c5813e64-9f1b-4b2f-956a-f591e75414e8.png)
