### ISSUE TITLE
Gracefully disconnect from a peripheral

### ISSUE THREAD

**Issue by 4lml4** [hdonk/javelin#3]
Hello, 

Thanks for this tool, it is extremely useful for connecting and interacting with BLE devices using Java on Windows. I was wondering if there was a way using Javelin to disconnect from a BLE peripheral? Currently I can connect to peripherals by querying the gatt services and characteristics, but am unable to disconnect without closing the program and waiting for the .dll file to close.

Thanks

**Comment by tofik2943** [comment]
I made custom classClassLoader to unload class. 

Library doesn't properly handle when device isnt nearby or was shut down during communication this needs not maintaining connection and closing resources in c++ in other cases unloading class is enough in Java

**Comment by 4lml4** [comment]
@tofik2943 thanks for that I will look into manually unloading the javelin class upon disconnection.

**Comment by 4lml4** [comment]
@tofik2943 could you suggest a custom ClassLoader tutorial? The resources I have found so far are quite old and don't seem to work. Thanks!

**Comment by tofik2943** [comment]
Custom ClassLoader:

`     class CustomClassLoader(dirPathString: String?) : ClassLoader() {
        private val searchPath: Path
        private val searchFile: File

    init {
        val path = Paths.get(dirPathString)
        require(Files.isDirectory(path)) { "Path must be a directory" }
        searchPath = path
        searchFile = File(dirPathString)
    }

    fun lsClasses(): Array<out File>? {
        return searchFile.listFiles { dir1: File?, name: String ->
            return@listFiles name.endsWith(".class")
        }
    }

    public override fun findClass(binName: String): Class<*> {
        val classFile = Paths.get(
            searchPath.toString() + FileSystems.getDefault().separator
                    + binName.replace(".", FileSystems.getDefault().separator) + ".class"
        )
        val buf: ByteArray
        buf = try {
            Files.readAllBytes(classFile)
        } catch (e: IOException) {
            throw ClassNotFoundException("Error in defining $binName in $searchPath", e)
        }
        return defineClass(binName, buf, 0, buf.size)
    }
}

`

You'll also need to make interface containing methods matching those in Javelin class and use javelin object as instance implementing this interface.

This is method loads javelin .class:


                fun construct(): JavelinStub {
                    resetCounterAndUnloadingTime()
                    while (retryLoadingDllsCounter < maxRetryLoadingDllsCounter) {
                        ccl = CustomClassLoader(parentDirectoryOfDirectoryWithJavelinClassFile)
                        //ccl!!.parent.clearAssertionStatus()
                        javelinClass = ccl!!.findClass("javelin.javelin")
                        try {
                            javelinStub = javelinClass!!.newInstance() as JavelinStub
                            return javelinStub!!
                        } catch (e: UnsatisfiedLinkError) {
                            println("Didn't load .dll trying $retryLoadingDllsCounter of $maxRetryLoadingDllsCounter")
                            extendWaitTimeAfterDestructing()
                            retryLoadingDllsCounter++
                            destruct()
                        }
                    }
                    throw CouldNotLoadBluetoothLowEnergyDll()
                }

**Comment by 4lml4** [comment]
Hi @tofik2943 

Thanks so much for the detailed response and all the info. I will have a go at the above and see how it goes. 

Thanks
